spring:
  datasource:
    url: jdbc:h2:mem:lmnr-api;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  h2:
     console:
       enabled: true
       path: /console
       settings:
         trace: false
         web-allow-others: false
  security:
    user:
      name: admin
      password: a
    oauth2:
      client:
        registration:
          azure:
            client-id: bf3b58ea-d086-47da-bdaf-5ddb2451e964
            client-secret: NfSIdTM7v56B3lV5DRI4ULwlAtxtdS7yD2VLAtvn6AI=

azure:
  activedirectory:
    tenant-id: eeaa8fd6-5ea7-4041-9b4e-41c068262640
    active-directory-groups: Users

lmnr-api:
    host: localhost
    port: 8082
    api_url: /contacts?id={id}